import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased py-20 px-42 bg-slate-100`}
      >
        <Link href="/">
          <button className="border rounded px-4 py-2 hover:border-2 hover:border-emerald-400 hover:cursor-pointer">
            Search By Ingredient
          </button>
        </Link>
        {children}
      </body>
    </html>
  );
}
