import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased py-2 px-8 md:py-8 md:px-42 bg-slate-100`}
      >
        <div className="flex gap-12 mb-10 ">
          <Link href="/">
            <button className="cursor-pointer">Home</button>
          </Link>
          <Link href="/search">
            <button className="cursor-pointer">Search By Ingredient</button>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
